export const initialOrderState = () => ({
  reserveTableNumber:0,
  pickUpNumber:0,
  createOrderLoading: false,
  createOrderFailure: false,
  createOrderLoaded: false,
  updateOrderLoading: false,
  updateOrderFailure: false,
  updateOrderLoaded: false,
  rateOrderLoading: false,
  rateOrderFailure: false,
  rateOrderLoaded: false,
  fetchOrderLoading: false,
  fetchOrderFailure: false,
  fetchOrderLoaded: false,
  fetchOrderByRestLoading: false,
  fetchOrderByRestFailure: false,
  fetchOrderByRestLoaded: false,
  fetchOrderByUserLoading: false,
  fetchOrderByUserFailure: false,
  fetchOrderByUserLoaded: false,
  fetchOrderItemDashboardLoading: false,
  fetchOrderItemDashboardFailure: false,
  fetchOrderItemDashboardLoaded: false,
});
