export const initialOrganizationState = () => ({
    createOrgLoading: false,
    createOrgFailure: false,
    createOrgLoaded: false,
    fetchOrgListLoading: false,
    fetchOrgListFailure: false,
    fetchOrgListLoaded: false,
    fetchOrgByIdLoading: false,
    fetchOrgByIdFailure: false,
    fetchOrgByIdLoaded: false,
    fetchOrgManuByIdLoading: false,
    fetchOrgManuByIdFailure: false,
    fetchOrgManuByIdLoaded: false,
    createManuLoading: false,
    createManuFailure: false,
    createManuLoaded: false,
    fetchManuByIdLoading: false,
    fetchManuByIdFailure: false,
    fetchManuByIdLoaded: false,
    cartItemQTY: 0,
    cartUpdateLoading: false,
    cartUpdateFailure: false,
    cartUpdateLoaded: false,
    fetchCartLoading: false,
    fetchCartFailure: false,
    fetchCartLoaded: false,
});
